import 'package:go_router/go_router.dart';

// `$prefabRoutes` is generated into product.prefab.g.dart by Prefab Flutter's
// RoutesGenerator. The import below provides it at runtime.
import '../models/product.prefab.g.dart';

/// Top-level [GoRouter] instance.
///
/// The `\$prefabRoutes` list is generated by Prefab Flutter and contains all
/// typed routes for every `@View`-annotated entity in the project.
final GoRouter appRouter = GoRouter(
  initialLocation: '/products',
  routes: [
    ...$prefabRoutes,
  ],
);
