// GENERATED CODE — DO NOT EDIT BY HAND
// ignore_for_file: type=lint
//
// This file is generated by Prefab Flutter from product.dart using @View, @Create, @Update, @Delete, @Api annotations.
// Run `flutter pub run build_runner build` to regenerate.

part of 'product.dart';

// ============================================================
// Routes  (RoutesGenerator)
// ============================================================

@TypedGoRoute<ProductListRoute>(
  path: '/products',
  routes: [
    TypedGoRoute<ProductDetailRoute>(path: ':id'),
    TypedGoRoute<ProductCreateRoute>(path: 'create'),
    TypedGoRoute<ProductEditRoute>(path: ':id/edit'),
  ],
)
class ProductListRoute extends GoRouteData {
  const ProductListRoute();

  @override
  Widget build(BuildContext context, GoRouterState state) =>
      const ProductListScreen();
}

class ProductDetailRoute extends GoRouteData {
  final String id;
  const ProductDetailRoute({required this.id});

  @override
  Widget build(BuildContext context, GoRouterState state) =>
      ProductDetailScreen(id: id);
}

class ProductCreateRoute extends GoRouteData {
  const ProductCreateRoute();

  @override
  Widget build(BuildContext context, GoRouterState state) =>
      const ProductCreateScreen();
}

class ProductEditRoute extends GoRouteData {
  final String id;
  const ProductEditRoute({required this.id});

  @override
  Widget build(BuildContext context, GoRouterState state) =>
      ProductEditScreen(id: id);
}

// ============================================================
// API client  (ApiClientGenerator)
// ============================================================

class ProductApiClient {
  final Dio _dio;
  final String _path = '/products';

  const ProductApiClient(this._dio);

  Future<PrefabPage<Product>> list({
    int page = 0,
    int size = 20,
    String search = '',
    String sortField = '',
    bool sortAscending = true,
  }) async {
    final response = await _dio.get(
      _path,
      queryParameters: {
        'page': page,
        'size': size,
        if (search.isNotEmpty) 'search': search,
        if (sortField.isNotEmpty) 'sort': '$sortField,${sortAscending ? 'asc' : 'desc'}',
      },
    );
    return PrefabPage.fromJson(
      response.data as Map<String, dynamic>,
      (json) => Product.fromJson(json as Map<String, dynamic>),
    );
  }

  Future<Product> getById(String id) async {
    final response = await _dio.get('$_path/$id');
    return Product.fromJson(response.data as Map<String, dynamic>);
  }

  Future<Product> create(Map<String, dynamic> body) async {
    final response = await _dio.post(_path, data: body);
    return Product.fromJson(response.data as Map<String, dynamic>);
  }

  Future<Product> update(String id, Map<String, dynamic> body) async {
    final response = await _dio.put('$_path/$id', data: body);
    return Product.fromJson(response.data as Map<String, dynamic>);
  }

  Future<void> delete(String id) async {
    await _dio.delete('$_path/$id');
  }
}

@riverpod
ProductApiClient productApiClient(ProductApiClientRef ref) {
  return ProductApiClient(ref.watch(dioProvider));
}

// ============================================================
// Riverpod providers  (ProviderGenerator)
// ============================================================

@riverpod
class ProductListNotifier extends _$ProductListNotifier {
  late final ProductApiClient _client;
  String _searchQuery = '';
  String _sortField = '';
  bool _sortAscending = true;
  int _page = 0;

  @override
  Future<PrefabPage<Product>> build() async {
    _client = ref.watch(productApiClientProvider);
    return _client.list(
      page: _page,
      search: _searchQuery,
      sortField: _sortField,
      sortAscending: _sortAscending,
    );
  }

  void search(String query) {
    _searchQuery = query;
    _page = 0;
    ref.invalidateSelf();
  }

  /// Sortable field names, derived from @ListColumn(sortable: true) annotations.
  /// Only these values are accepted by [sort] to prevent arbitrary sort injection.
  static const _allowedSortFields = {'name', 'price'};

  void sort(String field, bool ascending) {
    if (!_allowedSortFields.contains(field)) return;
    _sortField = field;
    _sortAscending = ascending;
    ref.invalidateSelf();
  }

  void nextPage() {
    _page++;
    ref.invalidateSelf();
  }

  void previousPage() {
    if (_page > 0) {
      _page--;
      ref.invalidateSelf();
    }
  }

  Future<void> create(String name, double price, String category) async {
    await _client.create({'name': name, 'price': price, 'category': category});
    ref.invalidateSelf();
    await future;
  }

  Future<void> update(String id, String name, double price, String category) async {
    await _client.update(id, {'name': name, 'price': price, 'category': category});
    ref.invalidateSelf();
    await future;
  }

  Future<void> delete(String id) async {
    await _client.delete(id);
    ref.invalidateSelf();
    await future;
  }
}

@riverpod
Future<Product> productDetail(ProductDetailRef ref, String id) {
  final client = ref.watch(productApiClientProvider);
  return client.getById(id);
}

// ============================================================
// List screen  (ListScreenGenerator)
// ============================================================

class ProductListScreen extends ConsumerWidget {
  const ProductListScreen({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final asyncItems = ref.watch(productListNotifierProvider);
    return Scaffold(
      appBar: AppBar(
        title: const Text('Products'),
        actions: const [PrefabSortMenu<Product>()],
      ),
      body: Column(
        children: [
          PrefabSearchBar(
            onChanged: (q) => ref.read(productListNotifierProvider.notifier).search(q),
          ),
          Expanded(
            child: asyncItems.when(
              data: (page) => _buildTable(context, ref, page),
              loading: () => const Center(child: CircularProgressIndicator()),
              error: (e, _) => Center(child: Text('Error: $e')),
            ),
          ),
          const PrefabPaginationBar<Product>(),
        ],
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => const ProductCreateRoute().push(context),
        child: const Icon(Icons.add),
      ),
    );
  }

  Widget _buildTable(
    BuildContext context,
    WidgetRef ref,
    PrefabPage<Product> page,
  ) {
    return SingleChildScrollView(
      scrollDirection: Axis.vertical,
      child: DataTable(
        columns: [
          DataColumn(
            label: const Text('Name'),
            onSort: (col, asc) =>
                ref.read(productListNotifierProvider.notifier).sort('name', asc),
          ),
          DataColumn(
            label: const Text('Price (€)'),
            onSort: (col, asc) =>
                ref.read(productListNotifierProvider.notifier).sort('price', asc),
          ),
          DataColumn(label: const Text('Category')),
        ],
        rows: page.items
            .map(
              (item) => DataRow(
                cells: [
                  DataCell(Text(item.name)),
                  DataCell(Text(item.price.toString())),
                  DataCell(Text(item.category)),
                ],
                onSelectChanged: (_) =>
                    ProductDetailRoute(id: item.id).push(context),
                onLongPress: () => _confirmDelete(context, ref, item.id),
              ),
            )
            .toList(),
      ),
    );
  }

  Future<void> _confirmDelete(
    BuildContext context,
    WidgetRef ref,
    String id,
  ) async {
    final confirmed = await showDialog<bool>(
      context: context,
      builder: (_) => const PrefabDeleteDialog<Product>(),
    );
    if (confirmed == true) {
      await ref.read(productListNotifierProvider.notifier).delete(id);
    }
  }
}

// ============================================================
// Create form screen  (FormScreenGenerator)
// ============================================================

class ProductCreateScreen extends ConsumerStatefulWidget {
  const ProductCreateScreen({super.key});

  @override
  ConsumerState<ProductCreateScreen> createState() =>
      _ProductCreateScreenState();
}

class _ProductCreateScreenState extends ConsumerState<ProductCreateScreen> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _priceController = TextEditingController();
  final _categoryController = TextEditingController();

  @override
  void dispose() {
    _nameController.dispose();
    _priceController.dispose();
    _categoryController.dispose();
    super.dispose();
  }

  Future<void> _submit() async {
    if (!_formKey.currentState!.validate()) return;
    try {
      await ref.read(productListNotifierProvider.notifier).create(
            _nameController.text,
            double.parse(_priceController.text),
            _categoryController.text,
          );
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Saved successfully')),
        );
        Navigator.of(context).pop();
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context)
            .showSnackBar(SnackBar(content: Text('Error: $e')));
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('New Product')),
      body: Padding(
        padding: const EdgeInsets.all(16),
        child: Form(
          key: _formKey,
          child: Column(
            children: [
              TextFormField(
                controller: _nameController,
                decoration: const InputDecoration(
                  labelText: 'Name',
                  hintText: 'Enter product name',
                ),
                validator: (v) =>
                    v == null || v.isEmpty ? 'Name is required' : null,
              ),
              TextFormField(
                controller: _priceController,
                decoration: const InputDecoration(
                  labelText: 'Price',
                  hintText: '0.00',
                ),
                keyboardType: TextInputType.number,
                validator: (v) =>
                    v == null || v.isEmpty ? 'Price is required' : null,
              ),
              TextFormField(
                controller: _categoryController,
                decoration: const InputDecoration(labelText: 'Category'),
              ),
              const SizedBox(height: 24),
              ElevatedButton(
                onPressed: _submit,
                child: const Text('Create'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

// ============================================================
// Edit form screen  (FormScreenGenerator)
// ============================================================

class ProductEditScreen extends ConsumerStatefulWidget {
  final String id;
  const ProductEditScreen({super.key, required this.id});

  @override
  ConsumerState<ProductEditScreen> createState() => _ProductEditScreenState();
}

class _ProductEditScreenState extends ConsumerState<ProductEditScreen> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _priceController = TextEditingController();
  final _categoryController = TextEditingController();

  @override
  void initState() {
    super.initState();
    _prefillControllers();
  }

  Future<void> _prefillControllers() async {
    final item = await ref.read(productDetailProvider(widget.id).future);
    setState(() {
      _nameController.text = item.name;
      _priceController.text = item.price.toString();
      _categoryController.text = item.category;
    });
  }

  @override
  void dispose() {
    _nameController.dispose();
    _priceController.dispose();
    _categoryController.dispose();
    super.dispose();
  }

  Future<void> _submit() async {
    if (!_formKey.currentState!.validate()) return;
    try {
      await ref.read(productListNotifierProvider.notifier).update(
            widget.id,
            _nameController.text,
            double.parse(_priceController.text),
            _categoryController.text,
          );
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Saved successfully')),
        );
        Navigator.of(context).pop();
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context)
            .showSnackBar(SnackBar(content: Text('Error: $e')));
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Edit Product')),
      body: Padding(
        padding: const EdgeInsets.all(16),
        child: Form(
          key: _formKey,
          child: Column(
            children: [
              TextFormField(
                controller: _nameController,
                decoration: const InputDecoration(
                  labelText: 'Name',
                  hintText: 'Enter product name',
                ),
                validator: (v) =>
                    v == null || v.isEmpty ? 'Name is required' : null,
              ),
              TextFormField(
                controller: _priceController,
                decoration: const InputDecoration(
                  labelText: 'Price',
                  hintText: '0.00',
                ),
                keyboardType: TextInputType.number,
                validator: (v) =>
                    v == null || v.isEmpty ? 'Price is required' : null,
              ),
              TextFormField(
                controller: _categoryController,
                decoration: const InputDecoration(labelText: 'Category'),
              ),
              const SizedBox(height: 24),
              ElevatedButton(
                onPressed: _submit,
                child: const Text('Save'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
