package be.appify.prefab.core.annotations;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Controls database migration script generation for an aggregate root.
 *
 * <p>Migration scripts are generated by default for every aggregate root when the {@code prefab-postgres}
 * module (or equivalent Spring Data JDBC dependency) is on the classpath. You only need this annotation
 * when you want to opt out of migration generation for a specific aggregate.</p>
 *
 * <p>To suppress migration generation for a specific aggregate, set {@code enabled = false}:</p>
 * <pre>{@code
 * @Aggregate
 * @DbMigration(enabled = false)
 * public record MyAggregate(...) {}
 * }</pre>
 *
 * <p>When {@code spring-boot-starter-data-jdbc} (or equivalent) is on the classpath a SQL script is
 * generated under {@code db/migration/}. When {@code spring-boot-starter-data-mongodb} (or equivalent)
 * is on the classpath a MongoDB JavaScript migration script is generated under
 * {@code mongo/migration/}.</p>
 */
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.SOURCE)
public @interface DbMigration {

    /**
     * Whether to generate a migration script for the annotated aggregate root.
     *
     * <p>Defaults to {@code true}. Set to {@code false} to opt out of migration generation.</p>
     *
     * @return {@code true} to generate migrations, {@code false} to suppress them
     */
    boolean enabled() default true;
}
