package be.appify.prefab.core.annotations;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Container annotation for multiple {@link Generate} overrides.
 *
 * <p>This annotation is automatically generated by the Java compiler when {@link Generate} is used
 * repeatably on the same type. Developers should not use this annotation directly.
 */
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.SOURCE)
public @interface GenerateOverrides {
    /**
     * The array of {@link Generate} annotations.
     *
     * @return array of Generate annotations
     */
    Generate[] value();
}

