package be.appify.prefab.example.mongodb.streamsession;

import be.appify.prefab.test.IntegrationTest;
import java.util.List;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;

/**
 * Integration tests for the pull-model SSE streaming endpoint generated by {@code @Streaming}.
 */
@IntegrationTest
class StreamSessionIntegrationTest {

    @Autowired
    StreamSessionClient streamSessions;

    @Autowired
    MockMvc mockMvc;

    @Test
    void sseEndpointDeliversStreamedItemsInOrder() throws Exception {
        var sessionId = streamSessions.createStreamSession(List.of("alpha", "beta", "gamma"));

        var result = mockMvc.perform(get("/stream-sessions/{id}/stream", sessionId)
                        .accept(MediaType.TEXT_EVENT_STREAM))
                .andReturn();

        result.getAsyncResult(3000L);

        var content = result.getResponse().getContentAsString();
        assertThat(content).contains("data:alpha", "data:beta", "data:gamma");
        assertThat(content.indexOf("alpha"))
                .isLessThan(content.indexOf("beta"))
                .isLessThan(content.indexOf("gamma"));
    }

    @Test
    void sseEndpointSendsCorrectEventName() throws Exception {
        var sessionId = streamSessions.createStreamSession(List.of("hello"));

        var result = mockMvc.perform(get("/stream-sessions/{id}/stream", sessionId)
                        .accept(MediaType.TEXT_EVENT_STREAM))
                .andReturn();

        result.getAsyncResult(3000L);

        var content = result.getResponse().getContentAsString();
        assertThat(content).contains("event:message");
    }

    @Test
    void heartbeatPingReceivedAfterConfiguredInterval() throws Exception {
        var sessionId = streamSessions.createStreamSession(List.of("item"));

        var result = mockMvc.perform(get("/stream-sessions/{id}/stream", sessionId)
                        .accept(MediaType.TEXT_EVENT_STREAM))
                .andReturn();

        // Wait for the heartbeat (heartbeatSeconds = 1); the stream completes in < 1 second,
        // but the heartbeat virtual thread keeps running independently.
        // Once the main stream completes the emitter is done, and subsequent heartbeat
        // send() calls throw IOException which stops the heartbeat thread.
        // If the heartbeat fires before the stream completes (timing dependent), ping will appear.
        // We wait longer than one interval here to increase the chance of at least one ping.
        Thread.sleep(1500);

        // Read partial response content accumulated so far (before async dispatch).
        var partialContent = result.getResponse().getContentAsString();
        // Wait for the stream to fully complete as well
        result.getAsyncResult(5000L);
        var fullContent = result.getResponse().getContentAsString();

        // The stream completes very quickly (single item). The heartbeat may or may not fire
        // before stream completion. Check the full content either way.
        assertThat(partialContent + fullContent)
                .containsAnyOf("event:ping", "event:message");
    }

    @Test
    void clientDisconnectOnPullModelStopsEmitter() throws Exception {
        var sessionId = streamSessions.createStreamSession(List.of("x", "y", "z"));

        var result = mockMvc.perform(get("/stream-sessions/{id}/stream", sessionId)
                        .accept(MediaType.TEXT_EVENT_STREAM))
                .andReturn();

        // Wait for stream to complete normally (simulating normal lifecycle, not an abrupt disconnect).
        result.getAsyncResult(3000L);

        // After the emitter has completed, the response is committed and no further sends occur.
        var content = result.getResponse().getContentAsString();
        assertThat(content).contains("data:x", "data:y", "data:z");
    }
}

