spring:
  application:
    name: prefab.mongodb-example
  data:
    mongodb:
      auto-index-creation: true

error.handling:
  exception-logging: WITH_STACKTRACE

topics:
  category.name: prefab.mongodb-example.category
  product.name: prefab.mongodb-example.product
