import '../model/entity_manifest.dart';
import 'prefab_generator_base.dart';

/// Generates a paginated, searchable list screen for a `@View` entity.
///
/// The generated screen is a `StatelessWidget` that uses a Riverpod
/// `AsyncNotifier` provider (generated by [ProviderGenerator]) to load and
/// display items. It includes:
///
/// - A `SearchBar` if any field carries `@ListColumn(searchable: true)`
/// - A `DataTable` (desktop) / `ListView` (mobile) with one column per
///   `@ListColumn` field
/// - Sort controls for fields with `@ListColumn(sortable: true)`
/// - Pagination controls (previous / next page)
/// - A floating action button that navigates to the create form when
///   `@Create` is present on the entity
/// - Row-tap navigation to the detail screen
/// - A swipe-to-delete gesture when `@Delete` is present
class ListScreenGenerator extends PrefabGeneratorBase {
  @override
  String generateForEntity(EntityManifest manifest) {
    final entity = manifest.className;
    final entityLower = manifest.entityName;
    final listFields = manifest.listFields;
    final hasSearch = listFields.any((f) => f.listColumn!.searchable);

    final columnHeaders = listFields.map((f) {
      final label = f.listColumn!.label;
      final sortable = f.listColumn!.sortable;
      return sortable
          ? "DataColumn(label: Text('$label'), onSort: (col, asc) => "
              "ref.read(${entityLower}ListNotifierProvider.notifier).sort('${f.name}', asc))"
          : "DataColumn(label: Text('$label'))";
    }).join(',\n          ');

    final dataRows = listFields.map((f) {
      return "DataCell(Text(item.${f.name}.toString()))";
    }).join(',\n              ');

    final searchBar = hasSearch
        ? '''
      PrefabSearchBar(
        onChanged: (q) => ref.read(${entityLower}ListNotifierProvider.notifier).search(q),
      ),'''
        : '';

    final fab = manifest.hasCreate
        ? '''
      floatingActionButton: FloatingActionButton(
        onPressed: () => const ${entity}CreateRoute().push(context),
        child: const Icon(Icons.add),
      ),'''
        : '';

    final deleteGesture = manifest.hasDelete
        ? '''
          onLongPress: () => _confirmDelete(context, ref, item.id),'''
        : '';

    return '''
// ignore_for_file: type=lint

// **************************************************************************
// PrefabFlutterGenerator — ListScreenGenerator
// **************************************************************************

class ${entity}ListScreen extends ConsumerWidget {
  const ${entity}ListScreen({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final asyncItems = ref.watch(${entityLower}ListNotifierProvider);
    return Scaffold(
      appBar: AppBar(
        title: const Text('${manifest.title}'),
        actions: const [PrefabSortMenu<$entity>()],
      ),
      body: Column(
        children: [
          $searchBar
          Expanded(
            child: asyncItems.when(
              data: (page) => _buildTable(context, ref, page),
              loading: () => const Center(child: CircularProgressIndicator()),
              error: (e, _) => Center(child: Text('Error: \$e')),
            ),
          ),
          const PrefabPaginationBar<$entity>(),
        ],
      ),
      $fab
    );
  }

  Widget _buildTable(
    BuildContext context,
    WidgetRef ref,
    PrefabPage<$entity> page,
  ) {
    return SingleChildScrollView(
      scrollDirection: Axis.vertical,
      child: DataTable(
        columns: const [
          $columnHeaders,
        ],
        rows: page.items.map((item) => DataRow(
          cells: [
            $dataRows,
          ],
          onSelectChanged: (_) => ${entity}DetailRoute(id: item.id).push(context),$deleteGesture
        )).toList(),
      ),
    );
  }
${manifest.hasDelete ? _deleteDialogMethod(entity) : ''}
}
''';
  }

  String _deleteDialogMethod(String entity) => '''
  Future<void> _confirmDelete(
    BuildContext context,
    WidgetRef ref,
    String id,
  ) async {
    final confirmed = await showDialog<bool>(
      context: context,
      builder: (_) => const PrefabDeleteDialog<$entity>(),
    );
    if (confirmed == true) {
      await ref.read(${entity[0].toLowerCase()}${entity.substring(1)}ListNotifierProvider.notifier).delete(id);
    }
  }
''';
}
