package be.appify.prefab.postgres.spring.data.jdbc;

import org.springframework.data.relational.core.mapping.DefaultNamingStrategy;
import org.springframework.data.relational.core.mapping.RelationalPersistentProperty;

import static be.appify.prefab.core.util.IdentifierShortener.columnName;
import static org.springframework.data.util.ParsingUtils.reconcatenateCamelCase;

/**
 * Custom NamingStrategy that includes the enclosing class name for inner classes, producing table names like "sale_line" instead of just
 * "line" for Sale.Line. This matches the table names generated by Prefab's DbMigrationWriter.
 * <p>
 * Column names are shortened to at most {@value be.appify.prefab.core.util.IdentifierShortener#POSTGRES_MAX_IDENTIFIER_LENGTH} characters, matching the identifiers
 * generated by Prefab's annotation processor and staying within PostgreSQL's identifier length limit.
 * </p>
 */
public class PrefabNamingStrategy extends DefaultNamingStrategy {

    @Override
    public String getTableName(Class<?> type) {
        return reconcatenateCamelCase(qualifiedSimpleName(type), "_");
    }

    @Override
    public String getColumnName(RelationalPersistentProperty property) {
        return columnName(property.getName());
    }

    private static String qualifiedSimpleName(Class<?> type) {
        Class<?> enclosing = type.getDeclaringClass();
        if (enclosing != null) {
            return qualifiedSimpleName(enclosing) + type.getSimpleName();
        }
        return type.getSimpleName();
    }
}
