package be.appify.prefab.postgres.spring.data.jdbc;

import org.springframework.data.relational.core.mapping.DefaultNamingStrategy;

import static org.springframework.data.util.ParsingUtils.reconcatenateCamelCase;

/**
 * Custom NamingStrategy that includes the enclosing class name for inner classes, producing table names like "sale_line" instead of just
 * "line" for Sale.Line. This matches the table names generated by Prefab's DbMigrationWriter.
 */
public class PrefabNamingStrategy extends DefaultNamingStrategy {

    /**
     * Constructs a new PrefabNamingStrategy.
     */
    public PrefabNamingStrategy() {
    }

    @Override
    public String getTableName(Class<?> type) {
        return reconcatenateCamelCase(qualifiedSimpleName(type), "_");
    }

    private static String qualifiedSimpleName(Class<?> type) {
        Class<?> enclosing = type.getDeclaringClass();
        if (enclosing != null) {
            return qualifiedSimpleName(enclosing) + type.getSimpleName();
        }
        return type.getSimpleName();
    }
}
