package be.appify.prefab.example.kafka.session;

import be.appify.prefab.core.service.Reference;
import be.appify.prefab.example.kafka.session.infrastructure.http.ChatSessionSseRegistry;
import be.appify.prefab.test.IntegrationTest;
import java.util.concurrent.TimeUnit;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.MediaType;
import org.springframework.kafka.core.KafkaTemplate;
import org.springframework.test.web.servlet.MockMvc;

import org.springframework.mock.web.MockAsyncContext;

import static org.assertj.core.api.Assertions.assertThat;
import static org.awaitility.Awaitility.await;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;

/**
 * Integration tests for the push-model SSE streaming endpoint generated by
 * {@code @Streaming} on an {@code @EventHandler @ByReference} method.
 */
@IntegrationTest
class ChatSessionIntegrationTest {

    @Autowired
    ChatSessionClient chatSessions;

    @Autowired
    MockMvc mockMvc;

    @Autowired
    ChatSessionSseRegistry sseRegistry;

    @Autowired
    KafkaTemplate<String, Object> kafkaTemplate;

    @Value("${topics.token.name}")
    String tokenTopic;

    @Test
    void kafkaEventFiresSsePayloadToConnectedClient() throws Exception {
        var sessionId = chatSessions.createChatSession("Test Session");

        var mvcResult = mockMvc.perform(get("/chat-sessions/{id}/stream", sessionId)
                        .accept(MediaType.TEXT_EVENT_STREAM))
                .andReturn();

        // Emitter is registered synchronously by the controller before returning.
        kafkaTemplate.send(tokenTopic, Reference.fromId(sessionId).toString(),
                new TokenEmitted(Reference.fromId(sessionId), "hello", false));
        kafkaTemplate.send(tokenTopic, Reference.fromId(sessionId).toString(),
                new TokenEmitted(Reference.fromId(sessionId), "world", true));

        // Wait for SSE to complete (terminal=true causes emitter.complete())
        mvcResult.getAsyncResult(30_000L);

        var content = mvcResult.getResponse().getContentAsString();
        assertThat(content).contains("data:hello", "data:world");
    }

    @Test
    void terminalEventClosesSseStream() throws Exception {
        var sessionId = chatSessions.createChatSession("Terminal Session");

        var mvcResult = mockMvc.perform(get("/chat-sessions/{id}/stream", sessionId)
                        .accept(MediaType.TEXT_EVENT_STREAM))
                .andReturn();

        kafkaTemplate.send(tokenTopic, Reference.fromId(sessionId).toString(),
                new TokenEmitted(Reference.fromId(sessionId), "last-token", true));

        // terminal=done=true must cause the SSE stream to close (emitter.complete())
        var asyncResult = mvcResult.getAsyncResult(30_000L);
        assertThat(asyncResult).isNull();  // emitter.complete() returns null result

        var content = mvcResult.getResponse().getContentAsString();
        assertThat(content).contains("data:last-token");
    }

    @Test
    void heartbeatPingReceivedAfterConfiguredInterval() throws Exception {
        var sessionId = chatSessions.createChatSession("Heartbeat Session");

        var mvcResult = mockMvc.perform(get("/chat-sessions/{id}/stream", sessionId)
                        .accept(MediaType.TEXT_EVENT_STREAM))
                .andReturn();

        // Wait longer than one heartbeat interval (heartbeatSeconds = 1)
        Thread.sleep(1500);

        // Send terminal event to close the SSE stream
        kafkaTemplate.send(tokenTopic, Reference.fromId(sessionId).toString(),
                new TokenEmitted(Reference.fromId(sessionId), "done", true));

        mvcResult.getAsyncResult(30_000L);

        var content = mvcResult.getResponse().getContentAsString();
        assertThat(content).contains("event:ping");
    }

    @Test
    void emitterRemovedFromRegistryAfterStreamCompletes() throws Exception {
        var sessionId = chatSessions.createChatSession("Disconnect Session");

        var mvcResult = mockMvc.perform(get("/chat-sessions/{id}/stream", sessionId)
                        .accept(MediaType.TEXT_EVENT_STREAM))
                .andReturn();

        // Emitter is registered synchronously by the controller before returning.
        assertThat(sseRegistry.findById(sessionId)).isPresent();

        // Capture the async context before dispatch so we can call complete() after.
        var asyncContext = (MockAsyncContext) mvcResult.getRequest().getAsyncContext();

        // Send a terminal event — this closes the SSE stream (emitter.complete() is called).
        kafkaTemplate.send(tokenTopic, Reference.fromId(sessionId).toString(),
                new TokenEmitted(Reference.fromId(sessionId), "closing", true));

        // Wait for the async result (DeferredResult is set when emitter.complete() is called)
        mvcResult.getAsyncResult(30_000L);

        // Simulate the servlet container calling asyncContext.complete() after the async dispatch.
        // In real containers this fires AsyncListener.onComplete(), which propagates to
        // DeferredResult / ResponseBodyEmitter onCompletion callbacks (registry.remove()).
        // MockMvc does NOT call complete() automatically after asyncDispatch.
        asyncContext.complete();

        await().atMost(2, TimeUnit.SECONDS).untilAsserted(() ->
                assertThat(sseRegistry.findById(sessionId)).isEmpty()
        );
    }
}

