package rest.withgeneratedevent;

import be.appify.prefab.core.annotations.Aggregate;
import be.appify.prefab.core.annotations.rest.Create;
import be.appify.prefab.core.annotations.rest.GetById;
import be.appify.prefab.core.service.Reference;
import jakarta.annotation.Nullable;
import jakarta.validation.constraints.NotNull;
import java.util.UUID;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.Version;

/**
 * Aggregate whose field type (OrderCreatedEvent) is generated by @Avsc in the same compilation round.
 * This causes the aggregate to be deferred to round 2 — the test verifies that the REST client is
 * still generated correctly in round 2 (i.e. TestJavaFileWriter.getRootPath() works even when
 * roundEnvironment.getRootElements() contains only generated elements).
 */
@Aggregate
@GetById
public record Order(
        @Id Reference<Order> id,
        @Version long version,
        @NotNull String description,
        @Nullable OrderCreatedEvent lastEvent
) {
    @Create
    public Order(@NotNull String description) {
        this(Reference.create(), 0L, description, null);
    }
}

