package be.appify.prefab.processor.tenant;

import be.appify.prefab.core.annotations.TenantId;
import be.appify.prefab.core.annotations.rest.Create;
import be.appify.prefab.core.annotations.rest.Update;
import be.appify.prefab.core.tenant.TenantContextProvider;
import be.appify.prefab.processor.ClassManifest;
import be.appify.prefab.processor.PrefabContext;
import be.appify.prefab.processor.PrefabPlugin;
import be.appify.prefab.processor.VariableManifest;
import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.MethodSpec;
import com.palantir.javapoet.ParameterizedTypeName;
import com.palantir.javapoet.TypeName;
import com.palantir.javapoet.TypeSpec;
import java.util.List;
import java.util.Optional;
import java.util.Set;
import javax.lang.model.element.Modifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import static org.apache.commons.text.WordUtils.capitalize;

/**
 * Plugin that provides multi-tenancy support via the {@link TenantId} annotation.
 *
 * <p>This plugin:</p>
 * <ul>
 *   <li>Validates that at most one {@code @TenantId} field is declared per aggregate (compile error otherwise).</li>
 *   <li>Validates that the {@code @TenantId} field does not appear in any generated request record
 *       ({@code @Create} constructor parameters or {@code @Update} method parameters).</li>
 *   <li>Registers {@link TenantContextProvider} as a service dependency so it is injected into the generated
 *       service class.</li>
 *   <li>Generates a {@code findBy<TenantField>(String, Pageable)} repository method for {@code @GetList}
 *       aggregates so the service can restrict list results to the current tenant.</li>
 * </ul>
 *
 * <p>The actual tenant-aware code in service methods (populate on write, filter on read) is generated by the
 * individual service writers which consult {@link ClassManifest#tenantIdField()}.</p>
 */
public class TenantPlugin implements PrefabPlugin {

    private PrefabContext context;

    /** Constructs a new TenantPlugin. */
    public TenantPlugin() {
    }

    @Override
    public void initContext(PrefabContext context) {
        this.context = context;
    }

    @Override
    public Set<TypeName> getServiceDependencies(ClassManifest manifest) {
        if (manifest.tenantIdField().isPresent()) {
            return Set.of(ClassName.get(TenantContextProvider.class));
        }
        return Set.of();
    }

    @Override
    public void writeRepository(ClassManifest manifest, TypeSpec.Builder builder) {
        manifest.tenantIdField().ifPresent(tenantField -> {
            if (!manifest.annotationsOfType(
                    be.appify.prefab.core.annotations.rest.GetList.class).isEmpty()) {
                builder.addMethod(MethodSpec.methodBuilder(
                                "findBy" + capitalize(tenantField.name()))
                        .addModifiers(Modifier.PUBLIC, Modifier.ABSTRACT)
                        .addParameter(String.class, tenantField.name())
                        .addParameter(Pageable.class, "pageable")
                        .returns(ParameterizedTypeName.get(
                                ClassName.get(Page.class), manifest.type().asTypeName()))
                        .build());
            }
        });
    }

    @Override
    public void writeAdditionalFiles(List<ClassManifest> manifests) {
        manifests.forEach(this::validate);
    }

    private void validate(ClassManifest manifest) {
        var tenantFields = manifest.fields().stream()
                .filter(f -> f.hasAnnotation(TenantId.class))
                .toList();

        if (tenantFields.size() > 1) {
            context.logError(
                    "Aggregate " + manifest.qualifiedName() + " declares more than one @TenantId field. "
                            + "Only one @TenantId field is allowed per aggregate.",
                    tenantFields.get(1).element());
            return;
        }

        if (tenantFields.isEmpty()) {
            return;
        }

        var tenantFieldName = tenantFields.getFirst().name();

        manifest.constructorsWith(Create.class).forEach(ctor ->
                ctor.getParameters().stream()
                        .filter(p -> p.getSimpleName().toString().equals(tenantFieldName))
                        .findFirst()
                        .ifPresent(p -> context.logError(
                                "@TenantId field '" + tenantFieldName + "' must not appear in a @Create "
                                        + "constructor. The tenant ID is populated automatically by the framework.",
                                p)));

        manifest.methodsWith(Update.class).forEach(method ->
                method.getParameters().stream()
                        .filter(p -> p.getSimpleName().toString().equals(tenantFieldName))
                        .findFirst()
                        .ifPresent(p -> context.logError(
                                "@TenantId field '" + tenantFieldName + "' must not appear in an @Update "
                                        + "method. The tenant ID is populated automatically by the framework.",
                                p)));
    }

    /**
     * Returns the tenant ID field for the given manifest, or empty if none is declared.
     *
     * @param manifest the class manifest
     * @return the tenant ID field, or empty
     */
    public static Optional<VariableManifest> tenantIdFieldOf(ClassManifest manifest) {
        return manifest.tenantIdField();
    }
}
